const WHITEICONSAPI=`../ASSETS/ICONS/WHITE/`;
const BLACKICONSAPI=`../ASSETS/ICONS/BLACK`;
const TEALICONSAPI=`../ASSETS/ICONS/TEAL/`;
const VIDEOSAPI=`../ASSETS/ICONS/TEAL/`;
const SOUNDSAPI=`../ASSETS/SOUNDS/`;
const IMAGESAPI=`../ASSETS/IMAGES/`;
const COUNTRIESAPI=`../DATABASE/Countries.json`;


export{WHITEICONSAPI,BLACKICONSAPI,TEALICONSAPI,VIDEOSAPI,SOUNDSAPI,IMAGESAPI,COUNTRIESAPI}